app:
  frontend:
    url: ${APP.FRONTEND.URL}
  cookie:
    secure: ${APP.COOKIE.SECURE:false}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: petdongne_server

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:petDongne_v2}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:

    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: update

      jdbc:
        time_zone: Asia/Seoul

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
        validator:
          apply_to_ddl: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - openid
              - profile_nickname
              - account_email
            client-name: kakao
        provider:
          kakao:
            issuer-uri: "https://kauth.kakao.com"
            jwk-set-uri: "https://kauth.kakao.com/.well-known/jwks.json"


# 스웨거 설정
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

# 로깅 설정
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG              # SQL 쿼리
    org.hibernate.type.descriptor.sql: TRACE  # 파라미터 값
    org:
      hibernate:
        event:
          internal: trace
      springframework:
        jdbc: trace
        orm: debug
#    root: debug

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL'
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
